language: "node_js"
node_js:
  - 12
script: "npm run build"
after_success:
  - echo "Uploading to FTP"
  - (cd dist ; find . -type d \( -path "./.*" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://ftp.fastmail.com/me.alduino.dev/files/subdomain/experiments --user $FTP_USER \; )