language: "node_js"
node_js:
  - 12
script: "npm run build"
after_success:
  - echo "Removing existing files"
  - curl -k ftp://ftp.fastmail.com/me.alduino.dev/files/subdomain/experiments --ftp-create-dirs --user "${SFTP_USER}:${STFP_PASSWORD}" -Q "-RMDIR /me.alduino.dev/files/subdomain/experiments"
  - echo "Uploading to FTP as ${SFTP_USER}"
  - find . -type d \( -path "./dist/.*" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://ftp.fastmail.com/me.alduino.dev/files/subdomain/experiments --user "${SFTP_USER}:${STFP_PASSWORD}" \;