after_success:
  - find . -type d \( -path "./dist/.*" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://fastmail.com/me/alduino.dev/files/subdomain/experiments --user ${SFTP_USER}:${STFP_PASSWORD} \;